# Allow faster key repetition.
set -sg escape-time 0

# Constrain window size to maximum size of any client connected to it.
setw -g aggressive-resize on

# No delay for escape key press.
set -sg escape-time 0

# Allow the mouse to be used for selecting panes etc.
set -g mouse on

# Set the default terminal mode to 256color mode.
setw -g xterm-keys on
set -g default-terminal 'xterm-256color'
set -ga terminal-overrides ',xterm*:Tc'

# Show the status bar at the top instead of the bottom.
set-option -g status-position top

# Set colorscheme.
ACTIVE='#d4d4d4'
ACTIVE_BG='#1f1e24'
INACTIVE='#5b5965'
INACTIVE_BG='#0a090e'

# Set left and right status bar.
set -g status-right ''
set -g status-right-fg $ACTIVE
set -g status-left '' # don't show current pane number

# Set default status bar colors.
set -g status-fg $INACTIVE
set -g status-bg $INACTIVE_BG

# Pane border and colors.
set -g pane-active-border-fg $ACTIVE
set -g pane-border-fg $INACTIVE

# Set window status.
window_status_format=" #I·#W "
set-window-option -g window-status-current-fg $ACTIVE
set-window-option -g window-status-current-bg $ACTIVE_BG
set -g window-status-current-format $window_status_format
set -g window-status-format $window_status_format
